## This script:
## 1. Reads files in nCompiler/R that have predefined nClass definitions.
## 2. Generates the .cpp and .h content in inst
library(nCompiler)

set_nOption("use_nCompLocal", TRUE)

if(!("generatePredefinedCpp.R" %in% list.files()))
  stop("You need source generatePredefinedCpp.R with its directory as your working directory.")

predefined_filebase <- "predefined"
clear_predefined_files <- function(compileAttributes = TRUE) {
  dir1 = file.path("nCompiler","src")
  dir2 = file.path("nCompiler","inst","include","nCompiler")
  for(dir in c(dir1, dir2)) {
    for(file in paste0(predefined_filebase, c(".h", ".cpp"))) {
      dirfile <- file.path(dir, file)
      if(file.exists(dirfile))
         file.remove(dirfile)
    }
  }
  if(compileAttributes)
    compileAttributes("nCompiler")
}

predefFiles <- c("zzz_NC_Predefined.R")
sourceDir <- file.path("nCompiler", "R")

predefinedNames <- character()
predefinedRcppPackets <- list()

getRcppPacket <- function(parsed, className) {
  env <- new.env()
  eval(parsed, envir = env)
  RcppPacket <- nCompile_nClass(env[[className]], 
                                control = list(endStage = 'writeCpp',
                                               filename = predefined_filebase))
  RcppPacket
}

for(pF in predefFiles) {
##  pF <- predefFiles[1]
  pathedFile <- file.path(sourceDir, pF)
  parsed <- parse(file = pathedFile)
  for(iP in seq_along(parsed)) {
    ##iP <- 1;
    thisParsed <- parsed[[iP]]
    
    if(is.call(thisParsed)) {
      if(deparse(thisParsed[[1]]) == "<-") {
        if(is.call(thisParsed[[3]])) {
          if(deparse(thisParsed[[3]][[1]]) == "nClass") {
            className <- deparse(thisParsed[[2]])
            predefinedNames <- append(predefinedNames, className)
            predefinedRcppPackets <- c(predefinedRcppPackets, 
                                       list(getRcppPacket(thisParsed, className)))
          }
        }
      }
    }
  }
}

sepContents <- function(x, element, label) 
  c("//--------------------------------------",
    "//--------------------------------------",
    paste0("// ", label),
    "//--------------------------------------",
    x[[element]]
  )

combinedPacket <- nCompiler:::Rcpp_nCompilerPacket(
  cppContent = c("//GENERATED BY generatedPredefinedCpp.R. DO NOT EDIT BY HAND",
    unlist(mapply(sepContents, 
           x = predefinedRcppPackets, 
           label = predefinedNames,
           MoreArgs = list(element = "cppContent"), 
           SIMPLIFY=FALSE, 
           USE.NAMES = FALSE))),
  hContent = c("//GENERATED BY generatedPredefinedCpp.R. DO NOT EDIT BY HAND",
    unlist(mapply(sepContents, 
           x = predefinedRcppPackets, 
           label = predefinedNames,
           MoreArgs = list(element = "hContent"), 
           SIMPLIFY=FALSE, 
           USE.NAMES = FALSE))),
  filebase = predefined_filebase
)

# Remove "// [[Rcpp::depends(nCompiler)]]"
# This should occur once per cppDef in cppContent
removeBool <- combinedPacket$cppContent == "// [[Rcpp::depends(nCompiler)]]"
combinedPacket$cppContent[removeBool] <- ""
# This should not occur in hContent, but we can defensively check anyway
removeBool <- combinedPacket$hContent == "// [[Rcpp::depends(nCompiler)]]"
combinedPacket$hContent[removeBool] <- ""

## remove any old files
clear_predefined_files(compileAttributes = FALSE)
nCompiler:::writeCpp_nCompiler(combinedPacket, dir = file.path("nCompiler","inst","include","nCompiler"))
nCompiler:::writeCpp_nCompiler(combinedPacket, dir = file.path("nCompiler","src"))
require(Rcpp)
compileAttributes("nCompiler")
