# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_value <- function(Xptr, name) {
    .Call('_nCompiler_get_value', PACKAGE = 'nCompiler', Xptr, name)
}

set_value <- function(Xptr, name, Svalue) {
    .Call('_nCompiler_set_value', PACKAGE = 'nCompiler', Xptr, name, Svalue)
}

call_method <- function(Xptr, name, Sargs) {
    .Call('_nCompiler_call_method', PACKAGE = 'nCompiler', Xptr, name, Sargs)
}

rcpp_hello_world <- function() {
    .Call('_nCompiler_rcpp_hello_world', PACKAGE = 'nCompiler')
}

