---
title: "Component Interactions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This page contains notes on how the various libraries and components used by `nCompiler` might interact. We need to think about:

- Eigen
- CppAD
- Cereal
- TBB
- R

##### Eigen + CppAD

These work fine.  We and others have used them together.

##### Eigen + Cereal

We need to serialize Eigen objects in cereal.  This should be straighforward. There is at least some code on the internet for doing so.

##### Eigen + TBB

When using TBB, we will be in control of when each thread needs a copy of an object and when they can share an object.

In cases where we could logically share an object, there is still a question of thread-safety.  Eigen claims that it is thread-safe by default.

TBB claims that other multi-thread systems can operate at the same time as it, so Eigen's own parallelization should be ok.

##### CppAD + Cereal

We create CppAD tapes upon DLL loading.  Hence we should not need to explicitly serialize the tapes but instead will rely on their re-creation each time a DLL is loaded.  There may be some cost to that, but on the other hand the tapes can be large, so not saving them seems like a good thing.

##### CppAD + TBB

This is a serious issue.  CppAD provides an interface for multi-threaded use.  It requires that the user be in charge of their own threads.  TBB takes charge of threads, so it doesn't work naturally with CppAD.  I have a system drafted [here](https://github.com/perrydv/TBB4CppAD).   Summary: I think I have this solved, but there are still some questions to be resolved.

##### Cereal + R

As mentioned in the serializiation page, we need to keep track of these two systems together.

##### TBB + R

It appears that we will need to adopt a thread-safe random-number generator.
