---
title: "Overview"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome

Welcome to nCompiler.  This package grew out of `nimble`, which includes a C++ code-generation system called the "nimble compiler".

This manual includes an overview of nCompiler's design, what works, and future plans.

For many features, the effort so far has been to create a skeleton of core functionality.  The goal is to see how the pieces fit together before fleshing them all out.

### [nFunctions and nClasses](nFunctions_and_nClasses.html)

#####      [Developer: nFunction and nClass internals](nFunctions_and_nClasses_internals.html)

### [Types and argument passing](types.html)

### [What can be compiled](what_can_be_compiled.html)

### [Managing C++ compilation](managing_compilation.html)

### [Saving and loading](saving_loading.html)

#####      [Developer: saving and loading internals](saving_loading_internals.html)

### [Using nCompiler code in packages](use_in_packages.html)

### [Automatic differentiation](automatic_differentiation.html)

### [Parallelization](parallelization.html)

### [Component interactions](component_interactions.html)

### [Extensibility and developer tools](extensibility_developer_tools.html)
