---
title: "What can be compiled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

What can be compiled in the body of an `nFunction` (including `nClass` methods)?

Eventually, `nCompiler` should support all the functionality of the `nimble` compiler and more.  This includes:

- most basic math, including vectorized math and linear algebra.
- most distribution functions, including recycling-rule behavior.
- simple for-loops.
- basic flow control, such as if-then-else and while.
- calling back to R functions from compiled code.
- calling external C (or other) libraries.
- Using more kinds of native R objects in compiled code.
- mixing hand-written C++ with nCompiler-generated C++.

The last two items are not in `nimble`.

For more detail about what `nimble` supports, see the [User Manual](https://r-nimble.org/documentation-2).

A fundamental shift from `nimble` to `nCompiler` is to make use of the Eigen C++ library not just for vectors and matrices but also for tensors (i.e. arrays).  This has enabled implementation of math with arrays.

What currently works includes much of the basic math and distribution functions, including component-wise operations on matrices and arrays and basic recycling-rule behavior for distributions.  There are some gaps to be filled in.  The current state of functionality should be reflected in `test-math.R`.

Basic for-loops, if-then-else, and while also work, but also have room for generalization.

Although the features supported for compilation are at the core of `nCompiler`'s usefulness, they are not the highest early development priority because they are similar to what works already in `nimble`.  For this reason, higher early priority is placed on writing skeletons for different `nCompiler` features.

Future plans include:

- Calling back to R functions from compiled code (similar to `nimble`).
- Calling externally compiled C (or other) code (similar to `nimble`).
- Use of native R objects if expected types are declared in code.  A good programming style for this needs consideration.
- Use of hand-coded C++ (including with Rcpp) that can interact easily with `nCompiler` objects. A good programming style for this needs consideration.

