// Regression tests for tensorStringNoTiling.h.
//
// Eigen's tiled (block-based) evaluation can materialize a block in raw,
// unconstructed scratch memory and assign std::string's into it, which is
// undefined behavior. It segfaults with libstdc++ (Linux) but usually works by
// luck with libc++ (macOS). These tests detect the problem on any platform:
// (1) at compile time, by checking which executor Eigen chooses, and
// (2) at run time, by forbidding Eigen heap allocations during the assignment.
// Tiled evaluation of these expressions requires a scratch allocation, but
// untiled evaluation does none.

// These must come before any Eigen include.
// EIGEN_RUNTIME_NO_MALLOC enables Eigen::internal::set_is_malloc_allowed().
// NCOMPILER_HANDLE_EIGEN_ERRORS makes eigen_assert throw (rather than being
// disabled by NDEBUG), so a forbidden allocation becomes a catchable error.
#define EIGEN_RUNTIME_NO_MALLOC
#define NCOMPILER_HANDLE_EIGEN_ERRORS

// [[Rcpp::plugins(nCompiler_Eigen_plugin)]]
// [[Rcpp::depends(nCompiler)]]
// [[Rcpp::depends(Rcereal)]]
#include "preamble.h"

template<typename L, typename R>
int isTileable(const L&, const R&) {
  typedef Eigen::TensorAssignOp<L, const R> Assign;
  return static_cast<int>(Eigen::internal::IsTileable<Eigen::DefaultDevice, const Assign>::value);
}

// Returns whether Eigen would use tiled evaluation for assignments of the
// forms that leak BlockAccess for std::string (chip or reshape of a raw tensor
// on both sides). The double versions of the same expressions should be tiled,
// which shows that the expressions do exercise the tiled path.
// [[Rcpp::export]]
Rcpp::IntegerVector stringNoTiling_isTileable() {
  Eigen::Tensor<std::string, 2> ys(2, 3), zs(2, 3);
  Eigen::Tensor<double, 2> yd(2, 3), zd(2, 3);
  Eigen::array<Eigen::Index, 1> off{{0}}, ext{{3}};
  Eigen::DSizes<Eigen::Index, 2> d32(3, 2);
  return Rcpp::IntegerVector::create(
    // y[1, 1:3] <- z[2, 1:3] (as generated by ISEQS_ and ISINGLE_)
    Rcpp::_["string_chip_slice"] = isTileable(ys.chip<0>(0).slice(off, ext), zs.chip<0>(1).slice(off, ext)),
    Rcpp::_["string_chip_reshape"] = isTileable(ys.chip<0>(0), zs.reshape(d32).chip<1>(0)),
    Rcpp::_["double_chip_slice"] = isTileable(yd.chip<0>(0).slice(off, ext), zd.chip<0>(1).slice(off, ext)),
    Rcpp::_["double_chip_reshape"] = isTileable(yd.chip<0>(0), zd.reshape(d32).chip<1>(0))
  );
}

// Runs the assignment with Eigen allocations forbidden.
// Returns the result and whether the assignment completed without allocating.
template<typename F>
bool runWithoutEigenMalloc(F f) {
  RESET_EIGEN_ERRORS
  bool ok = true;
  Eigen::internal::set_is_malloc_allowed(false);
  try {
    f();
  } catch(std::exception &e) {
    ok = false;
  }
  Eigen::internal::set_is_malloc_allowed(true);
  RESET_EIGEN_ERRORS
  return ok;
}

// y[1, 1:3] <- z[2, 1:3] for a 2 x 3 character matrix z.
// [[Rcpp::export]]
Rcpp::List stringNoTiling_assign2D(Eigen::Tensor<std::string, 2> z) {
  Eigen::Tensor<std::string, 2> y(2, 3);
  Eigen::array<Eigen::Index, 1> off{{0}}, ext{{3}};
  bool noScratch = runWithoutEigenMalloc([&]() {
    y.chip<0>(0).slice(off, ext) = z.chip<0>(1).slice(off, ext);
  });
  return Rcpp::List::create(Rcpp::_["y"] = y,
                            Rcpp::_["noScratch"] = noScratch);
}

// y[1, 2:3, 3:4] <- z[2, 1:2, 2:3] for a 2 x 3 x 4 character array z.
// [[Rcpp::export]]
Rcpp::List stringNoTiling_assign3D(Eigen::Tensor<std::string, 3> z) {
  Eigen::Tensor<std::string, 3> y(2, 3, 4);
  Eigen::array<Eigen::Index, 2> yOff{{1, 2}}, zOff{{0, 1}}, ext{{2, 2}};
  bool noScratch = runWithoutEigenMalloc([&]() {
    y.chip<0>(0).slice(yOff, ext) = z.chip<0>(1).slice(zOff, ext);
  });
  return Rcpp::List::create(Rcpp::_["y"] = y,
                            Rcpp::_["noScratch"] = noScratch);
}
