//#ifndef NCOMPILER_EIGENTENSOR_FORWARD_DECLARATIONS_H_
//#define NCOMPILER_EIGENTENSOR_FORWARD_DECLARATIONS_H_

#include <unsupported/Eigen/CXX11/Tensor>
#include "StridedTensorMap.h"

//#endif // NCOMPILER_EIGENTENSOR_FORWARD_DECLARATIONS_H_
