# .github/workflows/test-suites.yml
name: Test Suites

on:
  push:
    branches: [ main, master, devel ]
  pull_request:
    branches: [ main, master, devel ]

jobs:
  # Job 1: nCompile and specific operator tests
  test-nCompile:
    runs-on: ubuntu-latest
    name: nCompile and specific operator tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev

      - name: Run nCompile and other tests
        run: |
          testthat::test_dir("tests/testthat/uncompiled_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/nCompile_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/cpp_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/specificOp_tests", reporter = "progress")
        shell: Rscript {0}

  # Job 2: nClass, types and serialization tests
  test-nClass:
    runs-on: ubuntu-latest
    name: nClass, types and serialization tests

    env:
      RSPM: https://packagemanager.posit.co/cran/latest  # Enables Linux binaries from Posit
      R_KEEP_PKG_SOURCE: yes  # Keeps sources for debugging if needed

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Install extra packages
        run: |
          Rscript -e 'install.packages(c("devtools","gh","nimble","inline","numDeriv","pkgload","withr","rmarkdown","testthat"))'

      - name: Run nClass, types and serialization tests
        run: |
          testthat::test_dir("tests/testthat/nClass_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/types_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/serialization_tests", reporter = "progress")
        shell: Rscript {0}

  # Job 3: Math tests
  test-math:
    runs-on: ubuntu-latest
    name: Math Tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev

      - name: Run Math tests
        run: |
          testthat::test_dir("tests/testthat/math_tests", reporter = "progress")
        shell: Rscript {0}

  # Job 4: tensorOps
  test-tensorOps:
    runs-on: ubuntu-latest
    name: TensorOps Tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev

      - name: Run TensorOps tests
        run: |
          testthat::test_dir("tests/testthat/tensorOps_tests", reporter = "progress")
        shell: Rscript {0}
