# .github/workflows/test-suites.yml
name: Test Suites

on:
  workflow_dispatch:
    inputs:
      run_cache_only:
        description: 'Run and cache dependency installations only'
        required: true
        default: 'no'

env:
  RSPM: https://packagemanager.posit.co/cran/latest  # Enables Linux binaries from Posit
  R_KEEP_PKG_SOURCE: yes  # Keeps sources for debugging if needed


jobs:
  install-cache:
    runs-on: ubuntu-latest
    if: github.event.inputs.run_cache_only == 'yes' || github.event.inputs.run_cache_only == 'no'
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('nCompiler/DESCRIPTION', 'ci-extra-packages.txt') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps("nCompiler", dependencies = TRUE)'

      - name: Install extra packages
        run: |
          Rscript -e '
          pkgs <- readLines("ci-extra-packages.txt")
          new_pkgs <- pkgs[!pkgs %in% installed.packages()[,"Package"]]
          if(length(new_pkgs)) install.packages(new_pkgs)
          '

      - name: Install package
        run: R CMD INSTALL nCompiler
 
  # Job 1: nCompile and specific operator tests
  test-nCompile:
    runs-on: ubuntu-latest
    needs: install_cache
    if: github.event.inputs.run_cache_only == 'no'
    name: nCompile and specific operator tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('nCompiler/DESCRIPTION', 'ci-extra-packages.txt') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Run nCompile and other tests
        run: |
          testthat::test_dir("tests/testthat/uncompiled_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/nCompile_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/cpp_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/specificOp_tests", reporter = "progress")
        shell: Rscript {0}

  # Job 2: nClass, types and serialization tests
  test-nClass:
    runs-on: ubuntu-latest
    needs: install_cache
    if: github.event.inputs.run_cache_only == 'no'
    name: nClass, types and serialization tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('nCompiler/DESCRIPTION', 'ci-extra-packages.txt') }}
          restore-keys: ${{ runner.os }}-r-
      
      - name: Run nClass, types and serialization tests
        run: |
          testthat::test_dir("tests/testthat/nClass_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/types_tests", reporter = "progress")
          testthat::test_dir("tests/testthat/serialization_tests", reporter = "progress")
        shell: Rscript {0}

  # Job 3: Math tests
  test-math:
    runs-on: ubuntu-latest
    needs: install_cache
    if: github.event.inputs.run_cache_only == 'no'
    name: Math Tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('nCompiler/DESCRIPTION', 'ci-extra-packages.txt') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Run Math tests
        run: |
          testthat::test_dir("tests/testthat/math_tests", reporter = "progress")
        shell: Rscript {0}

  # Job 4: tensorOps
  test-tensorOps:
    runs-on: ubuntu-latest
    needs: install_cache
    if: github.event.inputs.run_cache_only == 'no'
    name: TensorOps Tests

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('nCompiler/DESCRIPTION', 'ci-extra-packages.txt') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Run TensorOps tests
        run: |
          testthat::test_dir("tests/testthat/tensorOps_tests", reporter = "progress")
        shell: Rscript {0}
